
// Empty Pipeline

pipeline {
    agent any 

    //environment {
        // Environment Variables to Add 
    //}

    options {
        timestamps ()
        timeout(time: 1, unit: 'HOURS')
    }


    // parameters {
        // Example of String 
        // string (name:'param_name', defaultValue: 'xx', description:'description')
        // Example of Choice
        // choice(name: 'param_name', choices: ['false', 'true'], description: 'description')  
    //}
    stages {

stage('checkout') {
                steps {

                    git branch: 'main', url: 'https://github.com/JudaB/my-code-example'
                } //steps
         } // Stage
       
stage('DockerBuild') {
    steps {
                        echo 'Compile the source code' 
                        app = docker.build("DevOps/ubuntu/hellonode")

                
                }//steps
            }// Execute TerraForm


stage('Test image') {
        /* Ideally, we would run a test framework against our image.
         * For this example, we're using a Volkswagen-type approach ;-) */

        app.inside {
            sh 'echo "Tests passed"'
        }


 stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
    } // Stages


post {
        failure {
            echo 'TODO: Fail Handler'
        }

        success {
            script {
                    echo 'TODO: Send Email'
                    
                }//script
        }

        always {
                    echo 'TBD: Always Handler'
        }//always
    }//post

    

}
