version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - internal_network
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - internal_network
      - bridged_network
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000/ram

networks:
  bridged_network:
    driver: bridge
  internal_network:
    driver: bridge
    internal: true
