# Default values for ramapi.
# This is a YAML-formatted file.

nginxHelloWorld:
  enabled: true
  image:  judab/nginx-hello-world:231204-23.03

rampi:
  enabled: false
  image: docker.io/judab/my-docker-example:211115-14.32


