{{- if .Values.nginxHelloWorld.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-world-web
  template:
    metadata:
      labels:
        app: nginx-hello-world-web
    spec:
      containers:
        - image: {{ .Values.nginxHelloWorld.image }}
          resources:
            requests:
              memory: 200m
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 800m
          name: nginx-app-container
          ports:
            - containerPort: 5000
{{- end }}

