
kind: Service
apiVersion: v1
metadata:
  name: my-deployment-service
spec:
  type: NodePort
  selector:
    app: rick_and_marty_web
  ports:
    - port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: my-deployment-service2
spec:
  selector:
    app: rick_and_marty_web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
