apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL:  https://judaB.github.io/my-code-example
    targetRevision: HEAD
    path: charts/ramapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook

